# Generated by Django 5.1.6 on 2025-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordersapp", "0003_alter_order_status_alter_order_table_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("В ожидании", "В ожидании"),
                    ("Готово", "Готово"),
                    ("Оплачено", "Оплачено"),
                ],
                db_index=True,
                default="В ожидании",
                max_length=10,
            ),
        ),
    ]
